//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssFeedWebhook {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class docker_compose : global::System.Configuration.ApplicationSettingsBase {
        
        private static docker_compose defaultInstance = ((docker_compose)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new docker_compose())));
        
        public static docker_compose Default {
            get {
                return defaultInstance;
            }
        }
    }
}
